### PR TITLE
Fix/page rules role check

### LINKED ISSUE #1425: Cannot set page-specific write permissions
I want some pages to be read-only and other pages to be writable. I set everything up as seen in the screenshot:

permissions

- the first rule is to start by denying everything
- then I allow specific access to the homepage the users are directed to when logging in (read-only)
- I allow full access to the users readwrite-area
- I allow read-only to a special immutable area.

For reading this works as expected (e.g. other existing pages cannot be opened). For writing only the global content permissions seem to have any effect. If I disable global write, the user cannot write on any pages, no matter what the page-specific permissions are. If I enable global write, the user can write to all pages they have read permissions on, no matter what other page-specific permissions are set. Any help would be greatly appreciated. Not sure if this a bug or a lack of understanding on my part.

### PR DESCRIPTION
**Pull request by bobonthenet**
This should resolve #1425

### CODE REVIEW

File: server/core/auth.js [hunk 1]
```diff
@@ -152,7 +152,7 @@ module.exports = {
    */
   checkAccess(user, permissions = [], page = false) {
     const userPermissions = user.permissions ? user.permissions : user.getGlobalPermissions()
-
+    const checkPermissions = permissions
```
Comment (nicolasg-playster) [inline server/core/auth.js]: Use `permissions` directly instead of creating a new copy. `_.intersection` does not mutate the original, so it's perfectly safe to use it directly.

File: server/core/auth.js [hunk 2]
```diff
@@ -173,26 +173,28 @@ module.exports = {
       user.groups.forEach(grp => {
         const grpId = _.isObject(grp) ? _.get(grp, 'id', 0) : grp
         _.get(WIKI.auth.groups, `${grpId}.pageRules`, []).forEach(rule => {
+          let hasRole = _.intersection(rule.roles, checkPermissions).length > 0
+
           switch (rule.match) {
             case 'START':
-              if (_.startsWith(`/${page.path}`, `/${rule.path}`)) {
+              if (_.startsWith(`/${page.path}`, `/${rule.path}`) && hasRole) {
```
Comment (nicolasg-playster) [inline server/core/auth.js]: Move `hasRole` at the beginning of the expression, so it's faster to exit the condition if false. ( repeat for other rules below )

File: server/core/auth.js (hunk 1 above)
Comment (bobonthenet) [reply server/core/auth.js]: For some reason I thought there was going to be a scoping issue. I just retried it though and I was mistaken.

File: server/core/auth.js (hunk 2 above)
Comment (bobonthenet) [reply server/core/auth.js]: I got rid of hasRole all together and wrapped the entire switch in an if statement that checks for the role in the permission with _.intersection.

**Comment by dakira** [comment]
Thanks a lot for this PR!
